### ISSUE TITLE
Implementation Layoutinformation

### ISSUE THREAD

**Issue by TruongQuangSB** [eclipse-set/set#3]
The Application should be able to evaluate and display the Layoutinformation, that stored in the layout.xml file within the .planpro container
- [x] Load Layoutinformation als EMF-Modell [pull-request#4](https://github.com/eclipse-set/set/pull/4)
- [x] Validate layout.xml [pull-request#15](https://github.com/eclipse-set/set/pull/15)
- [x] Standalone Textview for layout.xml [pull-request#16](https://github.com/eclipse-set/set/pull/16)
